{% set name = "google-cloud-artifact-registry" %}
{% set version = "1.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google-cloud-artifact-registry-{{ version }}.tar.gz
  sha256: 2deba5c9c0065cf8e2e63c547e93a4921867d57261d57d4a756be1031529e228

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/google-cloud-python
  summary: Google Cloud Artifact Registry API client library
  description: |
    Artifact Registry provides a single place for your organization to manage
    container images and language packages (such as Maven and npm).
    It is fully integrated with Google Cloud’s tooling and runtimes and comes
    with support for native artifact protocols. This makes it simple to
    integrate it with your CI/CD tooling to set up automated pipelines.
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE

  doc_url: https://cloud.google.com/python/docs/reference/artifactregistry/latest
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-artifact-registry


extra:
  recipe-maintainers:
    - cbcunc
